[{
		"code": "sco_lerelais_1",
		"nom": "BASSE-GOULAINE – La Poste",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.216567",
		"longitude": "-1.466988",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_2",
		"nom": "BOUAYE – Médiathèque",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.141605",
		"longitude": "-1.688792",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText"	: "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_3",
		"nom": "BOUAYE – Lycée",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.15593",
		"longitude": "-1.681448",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_4",
		"nom": "BOUGUENAIS  - Jardiland",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.174762",
		"longitude": "-1.609643",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_5",
		"nom": "BOUGUENAIS – Lidl",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.174515",
		"longitude": "-1.62393",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_6",
		"nom": "BOUGUENAIS – Prairie aux Prés",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.18065",
		"longitude": "-1.579425",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_7",
		"nom": "BOUGUENAIS – Rue Célestin Freinet",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.180882",
		"longitude": "-1.588231",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_8",
		"nom": "BOUGUENAIS – Rue de la Commune",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.17697",
		"longitude": "-1.61421",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_9",
		"nom": "BOUGUENAIS – Sobreda",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.187287",
		"longitude": "-1.587384",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_10",
		"nom": "BOUGUENAIS – Stade des Landes",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.175091",
		"longitude": "-1.5857",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_11",
		"nom": "BRAINS – Église",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "2",
		"latitude": "47.168614",
		"longitude": "-1.719921",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_12",
		"nom": "COUËRON – Le Relais",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "2",
		"latitude": "47.234908",
		"longitude": "-1.666844",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_13",
		"nom": "COUËRON – Parking Estuaire ",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.211191",
		"longitude": "-1.719866",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_14",
		"nom": "COUËRON – Super U",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "2",
		"latitude": "47.216079",
		"longitude": "-1.685009",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_15",
		"nom": "COUËRON – Église Saint-Éloi",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.21561",
		"longitude": "-1.678565",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_16",
		"nom": "LA CHAPELLE-SUR-ERDRE – Capellia",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.279782",
		"longitude": "-1.557147",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_17",
		"nom": "LA CHAPELLE-SUR-ERDRE – Géant Casino",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "2",
		"latitude": "47.284695",
		"longitude": "-1.551252",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_18",
		"nom": "LA MONTAGNE – Place Guérin",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.187686",
		"longitude": "-1.683135",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_19",
		"nom": "LA MONTAGNE – Shopi",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.187087",
		"longitude": "-1.68772",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_20",
		"nom": "LA MONTAGNE – Église",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.189839",
		"longitude": "-1.684207",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_21",
		"nom": "LE PELLERIN – La Poste",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.198203",
		"longitude": "-1.754081",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_22",
		"nom": "MAUVES-SUR-LOIRE – Déchèterie",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.313202",
		"longitude": "-1.411112",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_23",
		"nom": "NANTES – Carrefour La Beaujoire",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.256595",
		"longitude": "-1.512939",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_24",
		"nom": "NANTES – Déchèterie ",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.225771",
		"longitude": "-1.503966",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_25",
		"nom": "NANTES – Le Comptoir Solilab",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "2",
		"latitude": "47.200967",
		"longitude": "-1.571585",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_26",
		"nom": "NANTES – Écopoint Beaujoire",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.253997",
		"longitude": "-1.523433",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_27",
		"nom": "NANTES – Écopoint Chantenay",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.198379",
		"longitude": "-1.601848",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_28",
		"nom": "NANTES – Écopoint Dervallières",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.225424",
		"longitude": "-1.591564",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_29",
		"nom": "NANTES – Écopoint Viarme",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.222283",
		"longitude": "-1.564918",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_30",
		"nom": "ORVAULT – Déchèterie",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.257051",
		"longitude": "-1.633487",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_31",
		"nom": "REZÉ  - Déchèterie",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "3",
		"latitude": "47.159805",
		"longitude": "-1.535079",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_32",
		"nom": "REZÉ – E.Leclerc",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "2",
		"latitude": "47.193004",
		"longitude": "-1.572563",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_33",
		"nom": "SAINT-AIGNAN-DE-GRAND-LIEU – Utile",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.127206",
		"longitude": "-1.630765",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_34",
		"nom": "SAINT-HERBLAIN – Auchan",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "2",
		"latitude": "47.247162",
		"longitude": "-1.608473",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_35",
		"nom": "SAINT-HERBLAIN – Ave Berthelot",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.226644",
		"longitude": "-1.616787",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_36",
		"nom": "SAINT-HERBLAIN – Ave des Naudières",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.238183",
		"longitude": "-1.598048",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_37",
		"nom": "SAINT-HERBLAIN – Casino Bellevue",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.211178",
		"longitude": "-1.617295",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_38",
		"nom": "SAINT-HERBLAIN – Crémetterie",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.218384",
		"longitude": "-1.608025",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_39",
		"nom": "SAINT-HERBLAIN – François Mitterrand",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.213531",
		"longitude": "-1.648381",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_40",
		"nom": "SAINT-HERBLAIN – La Bernadière",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.206197",
		"longitude": "-1.614961",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_41",
		"nom": "SAINT-HERBLAIN – PAV Rue de la Gare",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.207772",
		"longitude": "-1.659269",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_42",
		"nom": "SAINT-HERBLAIN – Les Bigourettes",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.224918",
		"longitude": "-1.612651",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_43",
		"nom": "SAINT-JEAN-DE-BOISEAU – Les Genêts",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.192693",
		"longitude": "-1.725339",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_44",
		"nom": "SAINT-LÉGER-LES-VIGNES – Sacré Coeur",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.135717",
		"longitude": "-1.732269",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_45",
		"nom": "SAINT-SÉBASTIEN-SUR-LOIRE – Auchan",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "4",
		"latitude": "47.19206",
		"longitude": "-1.495526",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_46",
		"nom": "SAINT-SÉBASTIEN-SUR-LOIRE – La Martellière",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.198648",
		"longitude": "-1.527197",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_47",
		"nom": "SAINT-SÉBASTIEN-SUR-LOIRE – La Profondine",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.195963",
		"longitude": "-1.488662",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_48",
		"nom": "SAINT-SÉBASTIEN-SUR-LOIRE – Les Savarières",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.209336",
		"longitude": "-1.487174",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_49",
		"nom": "SAINT-SÉBASTIEN-SUR-LOIRE – Toys'R'Us",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.192852",
		"longitude": "1,493267",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_50",
		"nom": "SAINTE-LUCE-SUR-LOIRE – Boulangerie",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.274951",
		"longitude": "-1.467053",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_51",
		"nom": "SAUTRON – Sports",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "2",
		"latitude": "47.264746",
		"longitude": "-1.679711",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}, {
		"code": "sco_lerelais_52",
		"nom": "VERTOU – Décathlon",
		"modesCollecte": "smco_conteneurlerelais",
		"type": "Conteneur vêtements",
		"adresseTemp": "1",
		"latitude": "47.179804",
		"longitude": "-1.501874",
		"src": "Données envoyées par Le Relais Atlantique le 11/2016, ",
		"descr": "Tissus secs, propres ou sales, mis dans des sacs plastiques.",
		"image": "conteneur_le_relais_instructions_mini.png",
		"carteMarqueur": "5",
		"carteIcon": "assets/icons/marker-icon-orange.png",
		"cartePopupText": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>",
		"cartePopupText_en": "Conteneur vêtements<br/><i>Source : Le Relais Atlantique le 11/2016</i>"
	}]